# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
 build:
   branches:
     only:
     
   docker:
     # specify the version you desire here
     - image: circleci/openjdk:8-jdk

     # Specify service dependencies here if necessary
     # CircleCI maintains a library of pre-built images
     # documented at https://circleci.com/docs/2.0/circleci-images/
     # - image: circleci/postgres:9.4

   working_directory: ~/repo

   environment:
     # Customize the JVM maximum heap limit
     MAVEN_OPTS: -Xmx3200m

   steps:
     - checkout

     # Download and cache dependencies
     - restore_cache:
         keys:
         - v1-dependencies-{{ checksum "pom.xml" }}
         # fallback to using the latest cache if no exact match is found
         - v1-dependencies-
     - run:
         name: Does docker even exist
         command: docker -v
     - run:
         name: Install docker-compose
         command: |
           set -x
           sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
     - run:
         name: changing permission docker-compose-file
         command: sudo chmod +x /usr/local/bin/docker-compose
     - setup_remote_docker
     - run: mvn clean compile package
     - run: ls config-service/target
     - run:
         name: Start containers
         command: docker-compose up --build -d
     - run: docker logs repo_kafka_1
     - run: docker logs repo_zookeeper_1
     - run: mvn dependency:go-offline

     - save_cache:
         paths:
           - ~/.m2
         key: v1-dependencies-{{ checksum "pom.xml" }}

     # run tests!
     - run: mvn integration-test
